version: '2'
services:

  pure-ftpd:
    image: gists/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./volumes/ftpuser:/home/ftpuser
      - ./volumes/pureftpd:/etc/pureftpd
    restart: always